version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-backend-test-app
        container_name: laravel_backend_test_app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www/html/
        volumes:
            - .:/var/www/html:cached
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        ports:
            - "8000:80"
        networks:
            - daily_laravel
        command: >
            /bin/sh -c "php artisan migrate &&
                        php artisan db:seed &&
                        php artisan config:cache &&
                        php artisan route:cache &&
                        php artisan queue:work --sleep=3 --tries=3 &
                        php artisan schedule:work &
                        apache2-foreground"
        deploy:
            resources:
                limits:
                    cpus: '1.0'
                    memory: 1024M
                reservations:
                    cpus: '0.5'
                    memory: 512M

    db:
        image: postgres:13
        container_name: laravel_backend_test_db
        restart: unless-stopped
        environment:
            POSTGRES_DB: laravel
            POSTGRES_USER: laravel
            POSTGRES_PASSWORD: secret
        volumes:
            - daily_pgdata:/var/lib/postgresql/data
        networks:
            - daily_laravel

    redis:
        image: redis:alpine
        container_name: laravel_backend_test_redis
        restart: unless-stopped
        networks:
            - daily_laravel

networks:
    daily_laravel:
        driver: bridge

volumes:
    daily_pgdata:
        driver: local
